name: CI

on:
  push:
  pull_request:

jobs:
  win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          release: false
          update: true
          install: base-devel mingw-w64-i686-toolchain mingw-w64-i686-geos
      - shell: msys2 {0}
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: artifacts
  win-x64:
    needs: win-x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-geos
      - shell: msys2 {0}
        run: ./build.sh
      - uses: actions/download-artifact@v4
        with:
          name: win-x86
          path: artifacts
      - run: ./pack.cmd
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
      - run: ./test.cmd
